export const antennaOptions = [
  { id: "0", label: "アンテナなし", type: "アンテナなし", description: "とくぎを持たない代わりに、ステータスが伸びやすい。" },
  { id: "1", label: "ノックダウン", type: "攻撃", description: "敵1体をいちげきで倒す。突然死耐性が高いと効きにくい" },
  { id: "2", label: "いちげきKO", type: "攻撃", description: "敵1体をいちげきで倒す。ノックダウンより確率が高い。" },
  { id: "3", label: "きゅうしょづき", type: "攻撃", description: "敵1体をいちげきで倒す。いちげきKOより確率が高い。" },
  { id: "4", label: "みんなノックダウン", type: "攻撃", description: "敵全体をいちげきで倒す。突然死耐性が高いと効きにくい。" },
  { id: "5", label: "みんないちげきKO", type: "攻撃", description: "敵全体をいちげきで倒す。みんなノックダウンより確率が高い。" },
  { id: "6", label: "みんなきゅうしょづき", type: "攻撃", description: "敵全体をいちげきで倒す。みんないちげきKOより確率が高い。" },
  { id: "7", label: "みずでっぽう", type: "攻撃", description: "敵1体に水属性の攻撃。威力は小さい。" },
  { id: "8", label: "バケツのみず", type: "攻撃", description: "敵3体に水属性の攻撃。威力は小さい。" },
  { id: "9", label: "たかなみ", type: "攻撃", description: "敵全体に水属性の攻撃。威力は小さい。" },
  { id: "10", label: "らくせき", type: "攻撃", description: "敵1体に土属性の攻撃。威力は小さい。" },
  { id: "11", label: "いしつぶて", type: "攻撃", description: "敵3体に土属性の攻撃。威力は小さい。" },
  { id: "12", label: "マグニチュード3", type: "攻撃", description: "敵全体に土属性の攻撃。威力は小さい。" },
  { id: "13", label: "せいでんき", type: "攻撃", description: "敵1体に雷属性の攻撃。威力は小さい。" },
  { id: "14", label: "いなづま", type: "攻撃", description: "敵3体に雷属性の攻撃。威力は小さい。" },
  { id: "15", label: "ひゃくボルト", type: "攻撃", description: "敵全体に雷属性の攻撃。威力は小さい。" },
  { id: "16", label: "つむじかぜ", type: "攻撃", description: "敵1体に風属性の攻撃。威力は小さい。" },
  { id: "17", label: "ビルかぜ", type: "攻撃", description: "敵3体に風属性の攻撃。威力は小さい。" },
  { id: "18", label: "かまいたち", type: "攻撃", description: "敵全体に風属性の攻撃。威力は小さい。" },
  { id: "19", label: "ひのたま", type: "攻撃", description: "敵1体に火属性の攻撃。威力は小さい。" },
  { id: "20", label: "ばくはつ", type: "攻撃", description: "敵3体に火属性の攻撃。威力は小さい。" },
  { id: "21", label: "やまかじ", type: "攻撃", description: "敵全体に火属性の攻撃。威力は小さい。" },
  { id: "22", label: "とがったこおり", type: "攻撃", description: "敵1体に氷属性の攻撃。威力は小さい。" },
  { id: "23", label: "ロックアイス", type: "攻撃", description: "敵3体に氷属性の攻撃。威力は小さい。" },
  { id: "24", label: "あられ", type: "攻撃", description: "敵全体に氷属性の攻撃。威力は小さい。" },
  { id: "25", label: "おどかす", type: "攻撃", description: "敵1体に闇属性の攻撃。威力は小さい。" },
  { id: "26", label: "ダークボール", type: "攻撃", description: "敵3体に闇属性の攻撃。威力は小さい。" },
  { id: "27", label: "くろいきり", type: "攻撃", description: "敵全体に闇属性の攻撃。威力は小さい。" },
  { id: "28", label: "よわいこうせん", type: "攻撃", description: "敵1体に光属性の攻撃。威力は小さい。" },
  { id: "29", label: "スポットライト", type: "攻撃", description: "敵3体に光属性の攻撃。威力は小さい。" },
  { id: "30", label: "ふゆのひざし", type: "攻撃", description: "敵全体に光属性の攻撃。威力は小さい。" },
  { id: "31", label: "ちょっとかいふく", type: "回復", description: "仲間ひとりのHPを少し回復させる。" },
  { id: "32", label: "みんなちょっとかいふく", type: "回復", description: "仲間全員のHPを少し回復する。" },
  { id: "33", label: "げどく", type: "治療", description: "毒状態になっている仲間ひとりを治す。" },
  { id: "34", label: "みんなげどく", type: "治療", description: "毒状態になっている仲間全員を治す。" },
  { id: "35", label: "しびれとる", type: "治療", description: "マヒ状態になっている仲間ひとりを治す。" },
  { id: "36", label: "みんなしびれとる", type: "治療", description: "マヒ状態になっている仲間全員を治す。" },
  { id: "37", label: "めざめる", type: "治療", description: "眠り状態になっている仲間ひとりを治す。" },
  { id: "38", label: "みんなめざめる", type: "治療", description: "眠り状態になっている仲間全員を治す。" },
  { id: "39", label: "ぞくせいなおす", type: "治療", description: "属性以上になっている仲間ひとりを治す。" },
  { id: "40", label: "みんなぞくせいなおす", type: "治療", description: "属性異常になっている仲間全員を治す。" },
  { id: "41", label: "ぜんぶなおす", type: "治療", description: "属性異常、状態異常になっている仲間ひとりを治す。" },
  { id: "42", label: "みんなぜんぶなおす", type: "治療", description: "属性以上、状態異常になっている仲間全員を治す。" },
  { id: "43", label: "ちょっとふっかつ", type: "治療", description: "戦闘不能になっている仲間ひとりのHPを少し回復させて復活させる。" },
  { id: "44", label: "みんなちょっとふっかつ", type: "治療", description: "戦闘不能になっている仲間全員のHPを少し回復させて復活させる。" },
  { id: "45", label: "たくわえる", type: "増強", description: "自分の次の打撃攻撃の威力を2倍に上げる。最大32倍まで上がる。" },
  { id: "46", label: "すこしつよくなれ", type: "増強", description: "仲間ひとりの攻撃力を少しだけ上げる。" },
  { id: "47", label: "つよくなれ", type: "増強", description: "仲間ひとりの攻撃力をそこそこ上げる。" },
  { id: "48", label: "すごくつよくなれ", type: "増強", description: "仲間ひとりの攻撃力を大幅に上げる。" },
  { id: "49", label: "みんなつよめになれ", type: "増強", description: "仲間全員の攻撃力を少しだけ上げる。" },
  { id: "50", label: "みんなつよくなれ", type: "増強", description: "仲間全員の攻撃力をそこそこ上げる。" },
  { id: "51", label: "みんなムキムキ", type: "増強", description: "仲間全員の攻撃力を大幅に上げる。" },
  { id: "52", label: "すこしこうふん", type: "増強", description: "仲間ひとりを2ターン興奮状態にする。" },
  { id: "53", label: "こうふん", type: "増強", description: "仲間ひとりを3ターン興奮状態にする。" },
  { id: "54", label: "ながくこうふん", type: "増強", description: "仲間ひとりを4ターン興奮状態にする。" },
  { id: "55", label: "みんなすこしこうふん", type: "増強", description: "仲間全員を2ターン興奮状態にする。" },
  { id: "56", label: "みんなこうふん", type: "増強", description: "仲間全員を3ターン興奮状態にする。" },
  { id: "57", label: "みんなながくこうふん", type: "増強", description: "仲間全員を4ターン興奮状態にする。" },
  { id: "58", label: "すこしはやくなれ", type: "増強", description: "仲間ひとりの素早さを少しだけ上げる。" },
  { id: "59", label: "はやくなれ", type: "増強", description: "仲間ひとりの素早さをそこそこ上げる。" },
  { id: "60", label: "すごくはやくなれ", type: "増強", description: "仲間ひとりの素早さを大幅に上げる。" },
  { id: "61", label: "みんなはやめになれ", type: "増強", description: "仲間全員の素早さを少しだけ上げる。" },
  { id: "62", label: "みんなはやくなれ", type: "増強", description: "味方の素早さをそこそこ上げる。" },
  { id: "63", label: "みんなかぜになれ", type: "増強", description: "仲間全員の素早さを大幅に上げる。" },
  { id: "64", label: "すこしかわしやすい", type: "増強", description: "仲間ひとりの回避率を少しだけ上げる。" },
  { id: "65", label: "かわしやすい", type: "増強", description: "仲間ひとりの回避率をそこそこ上げる。" },
  { id: "66", label: "すごくかわしやすい", type: "増強", description: "仲間ひとりの回避率を大幅に上げる。" },
  { id: "67", label: "みんなあてられにくい", type: "増強", description: "仲間全員の回避率を少しだけ上げる。" },
  { id: "68", label: "みんなかわしやすい", type: "増強", description: "仲間全員の回避率をそこそこ上げる。" },
  { id: "69", label: "みんなでスルー", type: "増強", description: "仲間全員の回避率を大幅に上げる。" },
  { id: "70", label: "すこしかたくなれ", type: "増強", description: "仲間ひとりの防御力を少しだけ上げる。" },
  { id: "71", label: "かたくなれ", type: "増強", description: "仲間ひとりの防御力をそこそこ上げる。" },
  { id: "72", label: "すごくかたくなれ", type: "増強", description: "仲間ひとりの防御力を大幅に上げる。" },
  { id: "73", label: "みんなかたくなれ", type: "増強", description: "味方の防御力をそこそこ上げる。" },
  { id: "74", label: "みんなかためになれ", type: "増強", description: "仲間全員の防御力を少しだけ上げる。" },
  { id: "75", label: "みんなガチガチ", type: "増強", description: "仲間全員の防御力を大幅に上げる。" },
  { id: "76", label: "すこしむてき", type: "増強", description: "仲間ひとりを1~2ターン無敵状態にする。" },
  { id: "77", label: "むてき", type: "増強", description: "仲間ひとりを2~3ターン無敵状態にする。" },
  { id: "78", label: "ながくむてき", type: "増強", description: "仲間ひとりを3~4ターン無敵状態にする。" },
  { id: "79", label: "みんなすこしむてき", type: "増強", description: "仲間全体を1~2ターン無敵状態にする。" },
  { id: "80", label: "みんなむてき", type: "増強", description: "仲間全員を2~3ターン無敵状態にする。" },
  { id: "81", label: "みんなながくむてき", type: "増強", description: "仲間全員を3~4ターン無敵状態にする。" },
  { id: "82", label: "すこしねむらせる", type: "補助", description: "敵1体を少し眠らせる。2ターン有効。" },
  { id: "83", label: "ねむらせる", type: "補助", description: "敵1体を眠り状態にして動けなくする。3ターン有効。" },
  { id: "84", label: "ふかくねむらせる", type: "補助", description: "敵1体を眠り状態にして動けなくする。4ターン有効。" },
  { id: "85", label: "みんなすこしねむらせる", type: "補助", description: "敵全体を少し眠らせる。2ターン有効。" },
  { id: "86", label: "みんなねむらせる", type: "補助", description: "敵全体を眠り状態にして動けなくする。3ターン有効。" },
  { id: "87", label: "みんなふかくねむらせる", type: "補助", description: "敵全体を眠り状態にして動けなくする。4ターン有効。" },
  { id: "88", label: "すこししびれさせる", type: "補助", description: "敵1体をマヒ状態にして動けなくする。2ターン有効。" },
  { id: "89", label: "しびれさせる", type: "補助", description: "敵1体をマヒ状態にして動けなくする。3ターン有効。" },
  { id: "90", label: "すごくしびれさせる", type: "補助", description: "敵1体をマヒ状態にして動けなくする。4ターン有効。" },
  { id: "91", label: "みんなすこししびれさせる", type: "補助", description: "敵全体をマヒ状態にして動けなくする。2ターン有効。" },
  { id: "92", label: "みんなしびれさせる", type: "補助", description: "敵全体をマヒ状態にして動けなくする。3ターン有効。" },
  { id: "93", label: "みんなすごくしびれさせる", type: "補助", description: "敵全体をマヒ状態にして動けなくする。4ターン有効。" },
  { id: "94", label: "どくになれ", type: "補助", description: "敵1体を毒状態にする。" },
  { id: "95", label: "どくどくになれ", type: "補助", description: "敵1体を強い毒状態にする。" },
  { id: "96", label: "もうどくになれ", type: "補助", description: "敵1体を猛烈な毒状態にする。" },
  { id: "97", label: "みんなどくになれ", type: "補助", description: "敵全体を毒状態にする。" },
  { id: "98", label: "みんなどくどくになれ", type: "補助", description: "敵全体を強い毒状態にする。" },
  { id: "99", label: "みんなもうどくになれ", type: "補助", description: "敵全体を猛烈な毒状態にする。" },
  { id: "100", label: "みんなすこしよけにくい", type: "補助", description: "敵全体の回避率を少しだけ下げる。" },
  { id: "101", label: "みんなよけにくい", type: "補助", description: "敵全体の回避率をそこそこ下げる。" },
  { id: "102", label: "みんなすごくよけにくい", type: "補助", description: "敵全体の回避率を大幅に下げる。" },
  { id: "103", label: "すこしおそくなれ", type: "補助", description: "敵1体の素早さを少しだけ下げる。" },
  { id: "104", label: "おそくなれ", type: "補助", description: "敵1体の素早さをそこそこ下げる。" },
  { id: "105", label: "すごくおそくなれ", type: "補助", description: "敵1体の素早さを大幅に下げる。" },
  { id: "106", label: "みんなおそめになれ", type: "補助", description: "敵全体の素早さを少しだけ下げる。" },
  { id: "107", label: "みんなおそくなれ", type: "補助", description: "敵の素早さをそこそこ下げる。" },
  { id: "108", label: "みんなのろのろ", type: "補助", description: "敵全体の素早さを大幅に下げる。" },
  { id: "109", label: "すこしやわくなれ", type: "補助", description: "敵1体の防御力を少しだけ下げる。" },
  { id: "110", label: "やわくなれ", type: "補助", description: "敵1体の防御力をそこそこ下げる。" },
  { id: "111", label: "すごくやわくなれ", type: "補助", description: "敵1体の防御力を大幅に下げる。" },
  { id: "112", label: "みんなやわらかめ", type: "補助", description: "敵全体の防御力を少しだけ下げる。" },
  { id: "113", label: "みんなやわくなれ", type: "補助", description: "敵全体の防御力をそこそこ下げる。" },
  { id: "114", label: "みんなやわやわ", type: "補助", description: "敵全体の防御力を大幅に下げる。" },
  { id: "115", label: "すこしよわくなれ", type: "補助", description: "敵1体の攻撃力を少しだけ下げる。" },
  { id: "116", label: "よわくなれ", type: "補助", description: "敵1体の攻撃力をそこそこ下げる。" },
  { id: "117", label: "すごくよわくなれ", type: "補助", description: "敵1体の攻撃力を大幅に下げる。" },
  { id: "118", label: "みんなよわめになれ", type: "補助", description: "敵全体の攻撃力を少しだけ下げる。" },
  { id: "119", label: "みんなよわくなれ", type: "補助", description: "敵全体の攻撃力をそこそこ下げる。" },
  { id: "120", label: "みんなげきよわ", type: "補助", description: "敵全体の攻撃力を大幅に下げる。" },
  { id: "121", label: "すこしめかくし", type: "補助", description: "敵1体の視界を遮り攻撃を当たりにくくする。2ターン有効。" },
  { id: "122", label: "めかくし", type: "補助", description: "敵1体の視界を遮り攻撃を当たりにくくする。3ターン有効。" },
  { id: "123", label: "ながくめかくし", type: "補助", description: "敵1体の視界を遮り攻撃を当たりにくくする。4ターン有効。" },
  { id: "124", label: "みんなすこしめかくし", type: "補助", description: "敵全体の視界を遮り攻撃を当たりにくくする。2ターン有効。" },
  { id: "125", label: "みんなめかくし", type: "補助", description: "敵全体の視界を遮り攻撃を当たりにくくする。3ターン有効。" },
  { id: "126", label: "みんなながくめかくし", type: "補助", description: "敵全体の視界を遮り攻撃を当たりにくくする。4ターン有効。" },
  { id: "127", label: "むてきかいじょ", type: "補助", description: "敵の無敵を解除する。" },
  { id: "128", label: "むてきかいじょ+", type: "補助", description: "敵の無敵を強く解除する。" },
  { id: "129", label: "ちょっとあしもとガード", type: "お得", description: "ちょっとの間ダメージ床でダメージを受けなくなる。" },
  { id: "130", label: "そこそこあしもとガード", type: "お得", description: "そこそこの間ダメージ床でダメージを受けなくなる。" },
  { id: "131", label: "しばらくあしもとガード", type: "お得", description: "しばらくの間ダメージ床でダメージを受けなくなる。" },
  { id: "132", label: "ちょっとステルス", type: "お得", description: "ちょっとの間敵に見つからなくなる。" },
  { id: "133", label: "そこそこステルス", type: "お得", description: "そこそこの間敵に見つからなくなる。" },
  { id: "134", label: "しばらくステルス", type: "お得", description: "しばらくの間敵に見つからなくなる。" },
] as const;

export const headOptions = [
  { id: "0", label: "丸" },
  { id: "1", label: "三角" },
  { id: "2", label: "四角" },
  { id: "3", label: "横楕円" },
  { id: "4", label: "縦楕円" },
  { id: "5", label: "スライム" },
  { id: "6", label: "ホイップ" },
  { id: "7", label: "くま" },
  { id: "8", label: "玉ねぎ" },
  { id: "9", label: "六角" },
  { id: "10", label: "キラキラ" },
  { id: "11", label: "おにぎり" },
  { id: "12", label: "凹" },
  { id: "13", label: "凸" },
  { id: "14", label: "ブロック" },
  { id: "15", label: "せっけん" },
  { id: "16", label: "キャンディ" },
  { id: "17", label: "ヘッドホン" },
  { id: "18", label: "トゲ" },
  { id: "19", label: "ビーンズ" },
  { id: "20", label: "レモン" },
  { id: "21", label: "雫" },
  { id: "22", label: "イカ" },
  { id: "23", label: "ロケット" },
  { id: "24", label: "餅" },
  { id: "25", label: "タワー" },
  { id: "26", label: "つぼ" },
  { id: "27", label: "小籠包" },
  { id: "28", label: "炎" },
  { id: "29", label: "隕石" },
  { id: "30", label: "ねずみ" },
  { id: "31", label: "たれ耳" },
  { id: "32", label: "ねこ" },
  { id: "33", label: "ピエロ" },
  { id: "34", label: "いぬ" },
  { id: "35", label: "砦" },
  { id: "36", label: "金魚鉢" },
  { id: "37", label: "クワガタ" },
  { id: "38", label: "うさぎ" },
  { id: "39", label: "月" },
  { id: "40", label: "悪魔" },
  { id: "41", label: "お団子" },
  { id: "42", label: "星" },
  { id: "43", label: "ハート" },
  { id: "44", label: "土星" },
] as const;

export const colorOptions = [
  { id: "black", label: "黒" },
  { id: "red", label: "赤" },
  { id: "blue", label: "青" },
  { id: "yellow", label: "黄色" },
  { id: "orange", label: "橙色" },
  { id: "green", label: "緑" },
  { id: "lightblue", label: "水色" },
  { id: "white", label: "白" },
  { id: "purple", label: "紫" },
  { id: "silver", label: "銀" },
  { id: "gold", label: "金" },
  { id: "pink", label: "桃" },
] as const;
